[build]
	command  = "vite build"
	functions =  "netlify/functions"
	publish = "dist"
# for spas
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[dev]
    command  = "vite"
    port = 3000 # Port that the dev server will be listening on
    publish = "dist" # Folder with the static content for _redirect file

  # more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/